services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-java:latest
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

